name: Deploy Backend to Railway

on:
  push:
    branches: [main]
    paths:
      - 'apps/backend/**'
      - 'packages/types/**'
      - 'prisma/**'
      - 'package.json'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -g @railway/cli

      - name: Generate Prisma client
        run: npx prisma generate --schema=./prisma/schema.prisma

      - name: Build backend
        run: npm run build --workspace=@happiness-bomb/backend

      - name: Deploy to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 